apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-history-server
  namespace: spark-poc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeMode: Filesystem